"use client";
import {useState} from "react";
// V2 workspace will be wired to the student APIs in the next UI commit.
const skills=[["Algebra",.78],["Calculus",.56],["Probability",.41]] as const;
export default function Home(){
 const [problem,setProblem]=useState(""); const [mode,setMode]=useState<"socratic"|"solve">("socratic"); const [submitted,setSubmitted]=useState(false);
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="logo">∑</span><div><strong>MathTutor</strong><small>Adaptive Learning</small></div></div><nav><button className="active">Workspace</button><button>Practice</button><button>Mastery</button><button>Mistake Lab</button><button>Notebook</button></nav><div className="profile"><div className="avatar">D</div><div><strong>Student</strong><small>Personalized session</small></div></div></aside>
 <section className="workspace"><header><div><span className="eyebrow">LEARNING WORKSPACE</span><h1>What are you working on?</h1><p>Ask a question, upload a problem, or practice a weak skill.</p></div><div className="status"><i/> Agent ready</div></header>
 <div className="grid"><section className="card composer"><div className="mode-row"><button className={mode==="socratic"?"pill selected":"pill"} onClick={()=>setMode("socratic")}>Socratic tutor</button><button className={mode==="solve"?"pill selected":"pill"} onClick={()=>setMode("solve")}>Solve & explain</button></div><textarea value={problem} onChange={e=>setProblem(e.target.value)} placeholder="e.g. Help me understand why the derivative of x² is 2x..."/><div className="composer-footer"><span>⌘ Enter to send</span><button className="send" disabled={!problem.trim()} onClick={()=>setSubmitted(true)}>Ask MathTutor →</button></div>{submitted&&<div className="response"><span className="tag">PLAN · {mode==="socratic"?"GUIDED":"FULL SOLUTION"}</span><p>{mode==="socratic"?"Let’s start by identifying what changes when x changes. What do you think the slope of y = x² represents at a particular x?":"I’ll parse the problem, choose the least expensive reliable path, verify the mathematics independently, and then explain the result."}</p></div>}</section>
 <section className="card"><div className="card-title"><h2>Mastery</h2><span>View all →</span></div>{skills.map(([name,value])=><div className="skill" key={name}><div><strong>{name}</strong><span>{Math.round(value*100)}%</span></div><div className="bar"><i style={{width:`${value*100}%`}}/></div>)}<div className="next"><small>NEXT BEST ACTION</small><strong>Practice Probability</strong><p>Target your weakest skill with a medium problem.</p></div></section></div>
 <div className="bottom-grid"><section className="card"><div className="card-title"><h2>Learning loop</h2><span>Live</span></div><div className="steps"><b>1<br/><small>Diagnose</small></b><b>→</b><b>2<br/><small>Teach</small></b><b>→</b><b>3<br/><small>Practice</small></b><b>→</b><b>4<br/><small>Master</small></b></div></section><section className="card"><div className="card-title"><h2>Agent activity</h2><span>Trace</span></div><div className="activity"><span>✓</span> Intent classified <em>trace</em></div><div className="activity"><span>✓</span> Student model loaded <em>trace</em></div><div className="activity"><span>•</span> Waiting for problem <em>now</em></div></section></div></section></main>
}
